### ISSUE TITLE
FR: Obey Exclusion Lists

### ISSUE THREAD

**Issue by gebhard73** [CiscoSecurity/amp-05-windows-tune#5]
Hi,

it would be great to have the possibility that Diag Analyzer obeys the exclusions lists for creating the summary file (e.g. by a command line switch and / or another interactive question):
-> if file / process / path / ... is on the exclusion list: don't include it in the statistics nor in the summary file

This would help creating effective and tuning existing exclusion lists.

Bonus: add a special section in the summary file for all hits (files / processes / pths) against the exclusion list.

Any chance to have this added to the tool? Thanks.

**Comment by mafranks** [comment]
This is a relatively barebones tool so that capability would not be possible considering it doesn't have access to the full policy.xml.

If you're looking for better functionality, try this more comprehensive tool which requires authentication and can view the exclusions. 
https://github.com/CiscoSecurity/amp-05-health-checker-windows
